package Collector.enums;

public enum MenuCommand {
    LOAD_PLAYER,
    NEW_PLAYER,
    CHOOSE_PLAYER,
    LOCAL_GAME,
    LOCAL_BRAWL,
    EDIT_LOCAL_DECK,
    EDIT_ONLINE_DECK,
    CHANGE_HP,
    CHANGE_NAME,
    CARD_LIBRARY,
    DELETE_PLAYER,
    GO_BACK,
    KEYWORDS,
    ADD_CARDS,
    REMOVE_CARDS,
    BRAWL_SPIMOKY,
    BRAWL_RANDOM_HP,
    BRAWL_RANDOM_DECK,
    BRAWL_CURSED,
    BRAWL_BONANZA,
    BRAWL_NIGHTMARE,
    VIEW_GAMES,
    HOST_GAME,
    PLAY_ONLINE,
    CHOOSE_CARD
}
